SECTION_NAME_Y_TOLERANCE = 40
SAME_ROW_Y_TOLERANCE = 30
BOLD_INK_DENSITY_THRESHOLD = 0.35
CHECKBOX_FILL_THRESHOLD = 0.15
CHECKBOX_ASPECT_MIN = 0.7
CHECKBOX_ASPECT_MAX = 1.4
SECTION_BOX_ASPECT_MIN = 0.5
SECTION_BOX_MIN_HEIGHT = 30
MIN_BOX_AREA_RATIO = 0.01
MAX_BOX_AREA_RATIO = 0.95
OVERLAP_THRESHOLD = 0.5
MAX_CHECKBOX_DISTANCE = 100
TEXT_BOX_MARGIN = 2
MAX_Y_COORDINATE = int(1e9)

CANNY_THRESHOLD_LOW = 50
CANNY_THRESHOLD_HIGH = 150
CONTOUR_APPROX_EPSILON = 0.02
DILATE_KERNEL_SIZE = 3
BINARY_THRESHOLD = 200

HEADER_PATTERNS = [
    r"^SECTION\s*\d*",
    r"^PART\s*\d*",
    r".*INFORMATION.*",
    r".*DETAILS.*",
    r"^CONSENT\s*:?$",
    r".*REFERRAL.*",
    r"^[A-Z][A-Z\s]{2,}:$",
]

LABEL_SUFFIXES = [":", "?", "Name", "Date", "Address", "No", "Number"]
